### transforming code into idioatic python
- replace traditional index manupulation with python core looping
idiomatic


In [1]:
 # looping over a range of numbers - traditional approach
for i in [0,1,2,3,4,5]:
    print(i**2,end=" ")
    

0 1 4 9 16 25 

In [2]:
#idiomatic programming
for i in range(6):
    print(i**2,end=" ")

0 1 4 9 16 25 

### looping over a collection


In [4]:
colors=['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end=" ")

red green yellow purple 

In [5]:
for color in colors:
    print(color,end=" ")

red green yellow purple 

### looping backwards

In [6]:
colors=['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")

purple yellow green red 

In [9]:
for color in reversed(colors):
    print(color,end=" ")

purple yellow green red 

### looping in sorted list

In [11]:
colors=['red','green','yellow','purple']
for color in sorted(colors,reverse=True):
    print(color,end=" ")

yellow red purple green 

### 

- if x<=y and y<=z:
- if x<=y<=z:
- if x==True:
- if x:

### pandas

In [12]:
import pandas as pd

In [14]:
dt={'id':[11,12,13,14,15],
   'first_name':['A','B','C','D','E'],
   'company':['aa','bb','cc','dd','ee'],
   'address':['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt=pd.DataFrame(dt)

In [15]:
print(mydt)

   id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [20]:
import os
os.getcwd()

'C:\\Users\\exam'

In [29]:
os.chdir("C:\\Users\\exam") #save to certain location

In [30]:
mydt.to_csv('workingfile.csv',index=False)

In [34]:
pwd

'C:\\Users\\exam'

### reading the data from csv file

In [31]:
mydata=pd.read_csv('workingfile.csv')

In [32]:
print(mydata)


   id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [45]:
mydata1=pd.read_csv('workingfile.csv',skiprows=1,
                    names=["custid","name","company","address"])

In [46]:
print(mydata1)

   custid name company address
0      11    A      aa     Hyd
1      12    B      bb     Hyd
2      13    C      cc     Hyd
3      14    D      dd     Hyd
4      15    E      ee     Hyd


In [47]:
mydata1=pd.read_csv('workingfile.csv',skiprows=[1,2,3],
                    names=["custid","name","company","address"])

In [39]:
print(mydata1)

  custid        name  company  address
0     id  first_name  company  address
1     14           D       dd      Hyd
2     15           E       ee      Hyd


### print only two columns
### print the large value from cust id column--max
### print the least value from cust id column--min
### average of cust id column--sum(li)/len(li)


### numpy-working with multi dimensional array
- numpy arrays is a bit like python list
- numpy array is data structure of numpy lib
- it's a shortcut for numeric python or numerical python

In [48]:
mydata1=pd.read_csv('workingfile.csv',skipcols=['company','address']
                    names=["custid","name","company","address"])

SyntaxError: invalid syntax (<ipython-input-48-8f3aa974a91d>, line 2)

In [49]:
import numpy as np # import the numpy package


In [50]:
li=[1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [51]:
array=np.array(li)
print(array) #converts the list into array using np.array()

[1 2 3 4 5]


In [53]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [55]:
a1=np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [57]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [59]:
# read a number --19528
#print the large digit print the number
def printlarge(n):
    large=0
    while n !=0:
        r=n%10
        if large<r:
            large=r
        n=n//10
    return large
print(printlarge(19528))
print(printlarge(36372))

9
7
